### ISSUE TITLE
Feature: Search for Songs

### ISSUE THREAD

**Issue by KarenMTan** [cs130-w22/Group-A5#1]
## Epic
Allow users to nominate songs for their friends to vote on.

## User Stories
- [x] story #9 
- [x] Users should be able to search for songs on Spotify.
- [x] If the song already exists in the playlist, users can up-vote the song.
- [x] If the song does not already exist in the playlist, user can to nominate (add songs to the playlist) songs.
- [ ] (Remove songs from nomination.)
