### ISSUE TITLE
Feature: Display song list

### ISSUE THREAD

**Issue by KarenMTan** [cs130-w22/Group-A5#3]
## Epic
Display the list of songs that users have added.

## User Stories
- [x] Sort by most voted to least voted (updated each time there's a vote OR --). 
- [x] Story #9: User can scroll down the list, and vote on songs.
- [x] Story #9: Admin can remove songs from the list.
