### ISSUE TITLE
Feature: Invite other users to shared session

### ISSUE THREAD

**Issue by KarenMTan** [cs130-w22/Group-A5#4]
## Epic
Allow the Admin to invite other users with a QR Code.

## User Stories
- [ ] Story #10 
- [ ] Admin can share a URL to the new session to other users (through certain media?).
- [ ] Admin can generate QR Codes for new sessions.
- [ ] Users can scan the Admin's QR Code to join a session.
