### ISSUE TITLE
Feature: Play Playlist

### ISSUE THREAD

**Issue by KarenMTan** [cs130-w22/Group-A5#5]
## Epic
User should be able to play curated playlist (through the app).

## User Stories
- [ ] Story #9 
- [ ] Play audio from app (mp4/Spotify Web API).
- [ ] View playlist + queue of following songs.
- [ ] General play functions (pause, stop, skip, remove).
